### ISSUE TITLE
auto deduction only to const

### ISSUE THREAD

**Issue by mb1248** [pubby/flat#1]
There is an incompatibility to the std containers: 
The iterator is always `const`, so that writing to all elements via iterator loop is not possible.
```
#include "include/flat_set.hpp"
#include <iostream>

template <typename T> struct TD;

int main(int argc, char* argv[]) {
  fc::vector_set<int> set;

  set.insert(2);
  set.insert(1);

  for (auto& itr : set) {
    // TD<decltype(itr)> td;
    itr *=2;
  }

  for (auto& i : set) {
    std::cout << i << "\n";
  }
}
```
The type of `itr` is `<const int &>` but should `<int &>`.

**Comment by pubby** [comment]
This is mostly intended, for safety reasons.

To modify the underlying value, the pattern is to iterate the public member container instead:

```
for (auto& v : set.container) {
    v *=2;
}
```
You have to be careful while doing so to preserve the sortedness of the container. That's the safety reason I mentioned earlier, and the reason why iterators are const by default.

**Comment by mb1248** [comment]
Thanks for pointing out the sortedness. That's a valid point to have a `const` at least for set. It is working with the member container.

But what is with a map?
It is provides `<const std::pair<int, int>>` instead of `<std::pair<const int, int>>`. If the key is const it preserve the order.

Access via `.container` is working.

**Comment by pubby** [comment]
The underlying vector container in map has to store `std::pair<int, int>`. If it was `std::pair<const int, int>` then the container could not be sorted or assigned or various other things.

Unfortunately there's no safe way to cast `std::pair<int, int>` to `std::pair<const int, int>&` in C++ so that's why `const std::pair<int, int>` is given instead.

I mentioned `container`, but you can also use the `has` member function and the `underlying` public member of iterators to modify map values.

**Comment by mb1248** [comment]
Ok @pubby, thank you, I see the problem.

Creating a new `std::pair<const int, int&>` could maybe solve this, then the `int&` can refer to the second member of the pair element in the underlying vector container.
Well, creating a pair inside of an iterator for each element is not really a solution.

So I will carefully itearte over the underlaying container.
